#!/usr/bin/env python3
"""Regenerate site/content/sponsors/ from the maintainer's public GitHub
sponsors.

GitHub Sponsors data is GraphQL-only and every request needs a token; this
script uses the `gh` CLI's login when available, else a GITHUB_TOKEN env var
(no special scopes needed: the `sponsors` connection only returns sponsors
whose sponsorship is public).

Usage:
    python3 scripts/update-sponsors.py [github-login]   # default: Mariatta

It deletes previously generated files (recognized by the GENERATED marker)
and writes one markdown page per sponsor; hand-written files in the section,
including _index.md, are left alone. Re-run whenever sponsors change, or wire
it into CI with a read:user PAT as a secret (the default Actions token cannot
query sponsors).
"""
import json
import pathlib
import subprocess
import sys
import urllib.request

MARKER = "# GENERATED by scripts/update-sponsors.py, do not edit by hand."
DEFAULT_OUT = pathlib.Path(__file__).resolve().parent.parent / "site" / "content" / "sponsors"


def build_query(login):
    return (
        'query { user(login: "%s") { sponsors(first: 100) { nodes { '
        "... on User { login name avatarUrl url } "
        "... on Organization { login name avatarUrl url } } } } }" % login
    )


def fetch(login):
    query = build_query(login)
    try:
        r = subprocess.run(
            ["gh", "api", "graphql", "-f", f"query={query}"],
            capture_output=True, text=True, check=True,
        )
        return json.loads(r.stdout)
    except (FileNotFoundError, subprocess.CalledProcessError):
        import os
        token = os.environ.get("GITHUB_TOKEN")
        if not token:
            sys.exit("Need either an authenticated `gh` CLI or GITHUB_TOKEN.")
        req = urllib.request.Request(
            "https://api.github.com/graphql",
            data=json.dumps({"query": query}).encode(),
            headers={"Authorization": f"Bearer {token}"},
        )
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())


def toml_str(s):
    return '"' + (s or "").replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_sponsor(s, weight):
    name = s.get("name") or s["login"]
    return f"""+++
{MARKER}
title = {toml_str(name)}
weight = {weight}
role = "GitHub sponsor"
photo = {toml_str(s["avatarUrl"])}
description = "Sponsors Popular's maintainer on GitHub. Thank you!"
[[social]]
  label = "GitHub"
  icon = "fa-brands fa-github"
  url = {toml_str(s["url"])}
+++
"""


def write_pages(sponsors, out):
    """Regenerate marker-bearing files in `out`; returns (written, removed)."""
    out.mkdir(parents=True, exist_ok=True)
    removed = 0
    for f in out.glob("*.md"):
        if f.name != "_index.md" and MARKER in f.read_text():
            f.unlink()
            removed += 1
    for i, s in enumerate(sponsors, start=1):
        (out / f"{s['login'].lower()}.md").write_text(render_sponsor(s, i * 10))
    return len(sponsors), removed


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    login = argv[0] if argv else "Mariatta"
    data = fetch(login)
    if data.get("errors"):
        sys.exit(f"GraphQL error: {data['errors']}")
    sponsors = data["data"]["user"]["sponsors"]["nodes"]
    written, removed = write_pages(sponsors, DEFAULT_OUT)
    print(f"{login}: wrote {written} sponsor(s), removed {removed} stale file(s) in {DEFAULT_OUT}")


if __name__ == "__main__":
    main()
